feat: crud manager search
dyne/starters pull request #135
Opened 2023-07-19 14:36 UTC by phoebus-84

- chore: upgradde flowbite-svelte
- feat: initial implementation of search specifyng field
- feat: Crud Manager search

2023-07-19 16:50 UTC, puria requested changes
When the search bar is empty the filter should be reset!

2023-07-20 09:10 UTC, phoebus-84 commented
> When the search bar is empty the filter should be reset!

🪛 💻  fixed!

2023-07-26 13:52 UTC, puria approved these changes

2023-07-26 13:53 UTC, puria approved these changes

2023-07-26 13:53 UTC, merged